[project]
name = "acms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AzgarRiad", email = "azgarriad@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "google-genai>=2.24.0",
    "ollama>=0.6.2",
    "pandas>=3.0.5",
    "psycopg2>=2.9.13",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.52.4",
]

[project.scripts]
acms = "acms:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
